name: README.md 내용 읽기 워크플로우

on:
  push:
    branches:
      - main

jobs:
  read-readme:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 체크아웃 할때
        uses: actions/checkout@v4

      - name: Node.js 셋팅하기
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: workflow 디렉토리 형제관계에 있는 scripts 디렉토리에 있는 read-readme.js 파일 실행하기 
        run: |
          node .github/scripts/read-readme.js